# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Downtown Economic Intelligence Dashboard

# Author/Organization info to be displayed in the templates
author1:
  name: Mayor's Office of Performance and Innovation (OPI)
  url: https://opi.baltimorecity.gov

author:
  name: DowntownRISE
  url: https://www.downtownbaltimorerise.com/

# Base URL for GitHub Pages deployment
baseurl: '/dpob-dashboard'  # correct for project/repo pages

# Logos and Alt Text
logourl: '/images/DowntownRiseColor.jpg'
logoalt: The DowntownRISE Logo

logourl1: '/images/MBS Seal Logo.png'
logoalt1: The Mayor Logo

# Navigation (used for sidebar or menus)
navigation:
  - text: Introduction
    internal: true
    url: /
    
  - text: Data Dictionary
    internal: true
    url: /data-dictionary

# Repo list for homepage
repos:
  - name: dpob-github
    description: 
    url: https://github.com/balt-opi/dpob-dashboard

# Style Variables
brand_color: "#121f3f"
