# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Downtown Partnership of Baltimore Dashboard
# Author/Organization info to be displayed in the templates
author:
  name: Downtown Partnership of Baltimore (DPOB)
  url: https://godowntownbaltimore.com

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/dpob-dashboard'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/dpob-dashboard/images/dpob.jpg'
logoalt: The DPOB Logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: /dpob_introduction_page
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Data Dictionary
  internal: false
  url: https://github.com/DCgov/guides-template

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: dpob-github
  description: 
  url: https://github.com/balt-opi/dpob-dashboard

# Style Variables
brand_color: "#1EC181"
